const sampleData = {
  products: [
    // Men's Dress Shirts
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Hugo Boss Regular Fit Business Shirt',
      slug: 'hugo-boss-regular-fit-business-shirt',
      category: "Men's Dress Shirts",
      description: 'Professional excellence with German precision',
      images: [
        '/images/sample-products/p7-1.jpg',
        '/images/sample-products/p7-2.jpg',
      ],
      price: 125.00,
      brand: 'Hugo Boss',
      rating: 4.8,
      numReviews: 22,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Lacoste Solid Poplin Shirt',
      slug: 'lacoste-solid-poplin-shirt',
      category: "Men's Dress Shirts",
      description: 'French elegance meets everyday comfort',
      images: [
        '/images/sample-products/p8-1.jpg',
        '/images/sample-products/p8-2.jpg',
      ],
      price: 89.95,
      brand: 'Lacoste',
      rating: 4.4,
      numReviews: 15,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nautica Wrinkle-Resistant Dress Shirt',
      slug: 'nautica-wrinkle-resistant-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'Easy-care fabric perfect for busy professionals',
      images: [
        '/images/sample-products/p9-1.jpg',
        '/images/sample-products/p9-2.jpg',
      ],
      price: 49.99,
      brand: 'Nautica',
      rating: 4.1,
      numReviews: 9,
      stock: 15,
      isFeatured: false,
      banner: null,
    },

    // Men's Sweatshirts
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Nike Sportswear Club Fleece Hoodie',
      slug: 'nike-sportswear-club-fleece-hoodie',
      category: "Men's Sweatshirts",
      description: 'Classic comfort with iconic Nike styling',
      images: [
        '/images/sample-products/p10-1.jpg',
        '/images/sample-products/p10-2.jpg',
      ],
      price: 55.00,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 145,
      stock: 25,
      isFeatured: true,
      banner: 'banner-3.jpg',
    },
    {
      name: 'Adidas Essentials Hoodie',
      slug: 'adidas-essentials-hoodie',
      category: "Men's Sweatshirts",
      description: 'Cozy warmth with the iconic three stripes',
      images: [
        '/images/sample-products/p11-1.jpg',
        '/images/sample-products/p11-2.jpg',
      ],
      price: 65.00,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 98,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Champion Powerblend Crewneck Sweatshirt',
      slug: 'champion-powerblend-crewneck-sweatshirt',
      category: "Men's Sweatshirts",
      description: 'Reduced pilling with heavyweight fleece',
      images: [
        '/images/sample-products/p12-1.jpg',
        '/images/sample-products/p12-2.jpg',
      ],
      price: 35.00,
      brand: 'Champion',
      rating: 4.6,
      numReviews: 234,
      stock: 50,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Under Armour Rival Fleece Hoodie',
      slug: 'under-armour-rival-fleece-hoodie',
      category: "Men's Sweatshirts",
      description: 'Light, breathable, and ultra-comfortable',
      images: [
        '/images/sample-products/p13-1.jpg',
        '/images/sample-products/p13-2.jpg',
      ],
      price: 45.00,
      brand: 'Under Armour',
      rating: 4.4,
      numReviews: 67,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'The North Face Drew Peak Hoodie',
      slug: 'the-north-face-drew-peak-hoodie',
      category: "Men's Sweatshirts",
      description: 'Outdoor heritage meets urban style',
      images: [
        '/images/sample-products/p14-1.jpg',
        '/images/sample-products/p14-2.jpg',
      ],
      price: 75.00,
      brand: 'The North Face',
      rating: 4.8,
      numReviews: 89,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Carhartt Midweight Hooded Sweatshirt',
      slug: 'carhartt-midweight-hooded-sweatshirt',
      category: "Men's Sweatshirts",
      description: 'Workwear durability for everyday wear',
      images: [
        '/images/sample-products/p15-1.jpg',
        '/images/sample-products/p15-2.jpg',
      ],
      price: 59.99,
      brand: 'Carhartt',
      rating: 4.9,
      numReviews: 312,
      stock: 35,
      isFeatured: false,
      banner: null,
    },

    // Men's Casual Shirts
    {
      name: 'Levi\'s Classic Western Denim Shirt',
      slug: 'levis-classic-western-denim-shirt',
      category: "Men's Casual Shirts",
      description: 'Authentic denim with snap buttons',
      images: [
        '/images/sample-products/p16-1.jpg',
        '/images/sample-products/p16-2.jpg',
      ],
      price: 69.50,
      brand: 'Levi\'s',
      rating: 4.6,
      numReviews: 78,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Patagonia Organic Cotton Flannel',
      slug: 'patagonia-organic-cotton-flannel',
      category: "Men's Casual Shirts",
      description: 'Sustainable comfort for cool weather',
      images: [
        '/images/sample-products/p17-1.jpg',
        '/images/sample-products/p17-2.jpg',
      ],
      price: 89.00,
      brand: 'Patagonia',
      rating: 4.7,
      numReviews: 54,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Columbia PFG Bahama Short Sleeve',
      slug: 'columbia-pfg-bahama-short-sleeve',
      category: "Men's Casual Shirts",
      description: 'Fishing shirt with UPF 30 sun protection',
      images: [
        '/images/sample-products/p18-1.jpg',
        '/images/sample-products/p18-2.jpg',
      ],
      price: 45.00,
      brand: 'Columbia',
      rating: 4.5,
      numReviews: 123,
      stock: 28,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'J.Crew Vintage Oxford Shirt',
      slug: 'jcrew-vintage-oxford-shirt',
      category: "Men's Casual Shirts",
      description: 'Preppy classic with modern fit',
      images: [
        '/images/sample-products/p19-1.jpg',
        '/images/sample-products/p19-2.jpg',
      ],
      price: 79.50,
      brand: 'J.Crew',
      rating: 4.3,
      numReviews: 41,
      stock: 13,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Uniqlo Linen Blend Long Sleeve Shirt',
      slug: 'uniqlo-linen-blend-long-sleeve-shirt',
      category: "Men's Casual Shirts",
      description: 'Breathable and lightweight for summer',
      images: [
        '/images/sample-products/p20-1.jpg',
        '/images/sample-products/p20-2.jpg',
      ],
      price: 39.90,
      brand: 'Uniqlo',
      rating: 4.4,
      numReviews: 167,
      stock: 42,
      isFeatured: false,
      banner: null,
    },

    // Men's Jeans
    {
      name: 'Levi\'s 501 Original Fit Jeans',
      slug: 'levis-501-original-fit-jeans',
      category: "Men's Jeans",
      description: 'The iconic straight fit jean since 1873',
      images: [
        '/images/sample-products/p21-1.jpg',
        '/images/sample-products/p21-2.jpg',
      ],
      price: 89.50,
      brand: 'Levi\'s',
      rating: 4.8,
      numReviews: 456,
      stock: 32,
      isFeatured: true,
      banner: 'banner-4.jpg',
    },
    {
      name: 'Wrangler Cowboy Cut Original Fit',
      slug: 'wrangler-cowboy-cut-original-fit',
      category: "Men's Jeans",
      description: 'Western heritage with authentic styling',
      images: [
        '/images/sample-products/p22-1.jpg',
        '/images/sample-products/p22-2.jpg',
      ],
      price: 49.99,
      brand: 'Wrangler',
      rating: 4.6,
      numReviews: 189,
      stock: 24,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'True Religion Rocco Skinny Jeans',
      slug: 'true-religion-rocco-skinny-jeans',
      category: "Men's Jeans",
      description: 'Premium denim with signature stitching',
      images: [
        '/images/sample-products/p23-1.jpg',
        '/images/sample-products/p23-2.jpg',
      ],
      price: 199.00,
      brand: 'True Religion',
      rating: 4.5,
      numReviews: 67,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Diesel Sleenker Skinny Jeans',
      slug: 'diesel-sleenker-skinny-jeans',
      category: "Men's Jeans",
      description: 'Italian craftsmanship with edgy style',
      images: [
        '/images/sample-products/p24-1.jpg',
        '/images/sample-products/p24-2.jpg',
      ],
      price: 178.00,
      brand: 'Diesel',
      rating: 4.4,
      numReviews: 52,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'AG Adriano Goldschmied Graduate Jeans',
      slug: 'ag-adriano-goldschmied-graduate-jeans',
      category: "Men's Jeans",
      description: 'Tailored fit with premium stretch',
      images: [
        '/images/sample-products/p25-1.jpg',
        '/images/sample-products/p25-2.jpg',
      ],
      price: 188.00,
      brand: 'AG',
      rating: 4.7,
      numReviews: 38,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Lee Regular Fit Straight Leg Jeans',
      slug: 'lee-regular-fit-straight-leg-jeans',
      category: "Men's Jeans",
      description: 'Classic comfort at an affordable price',
      images: [
        '/images/sample-products/p26-1.jpg',
        '/images/sample-products/p26-2.jpg',
      ],
      price: 44.99,
      brand: 'Lee',
      rating: 4.3,
      numReviews: 234,
      stock: 45,
      isFeatured: false,
      banner: null,
    },

    // Men's Jackets
    {
      name: 'The North Face Denali Fleece Jacket',
      slug: 'the-north-face-denali-fleece-jacket',
      category: "Men's Jackets",
      description: 'Iconic fleece jacket built for warmth',
      images: [
        '/images/sample-products/p27-1.jpg',
        '/images/sample-products/p27-2.jpg',
      ],
      price: 179.00,
      brand: 'The North Face',
      rating: 4.9,
      numReviews: 312,
      stock: 15,
      isFeatured: true,
      banner: 'banner-5.jpg',
    },
    {
      name: 'Patagonia Better Sweater Jacket',
      slug: 'patagonia-better-sweater-jacket',
      category: "Men's Jackets",
      description: 'Cozy fleece with Fair Trade certification',
      images: [
        '/images/sample-products/p28-1.jpg',
        '/images/sample-products/p28-2.jpg',
      ],
      price: 139.00,
      brand: 'Patagonia',
      rating: 4.8,
      numReviews: 267,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Columbia Interchange 3-in-1 Jacket',
      slug: 'columbia-interchange-3-in-1-jacket',
      category: "Men's Jackets",
      description: 'Versatile system for all weather conditions',
      images: [
        '/images/sample-products/p29-1.jpg',
        '/images/sample-products/p29-2.jpg',
      ],
      price: 150.00,
      brand: 'Columbia',
      rating: 4.6,
      numReviews: 143,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Carhartt Duck Detroit Jacket',
      slug: 'carhartt-duck-detroit-jacket',
      category: "Men's Jackets",
      description: 'Rugged workwear for serious conditions',
      images: [
        '/images/sample-products/p30-1.jpg',
        '/images/sample-products/p30-2.jpg',
      ],
      price: 99.99,
      brand: 'Carhartt',
      rating: 4.7,
      numReviews: 198,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Barbour Bedale Wax Jacket',
      slug: 'barbour-bedale-wax-jacket',
      category: "Men's Jackets",
      description: 'British heritage with waterproof waxed cotton',
      images: [
        '/images/sample-products/p31-1.jpg',
        '/images/sample-products/p31-2.jpg',
      ],
      price: 399.00,
      brand: 'Barbour',
      rating: 4.9,
      numReviews: 87,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Alpha Industries MA-1 Flight Jacket',
      slug: 'alpha-industries-ma1-flight-jacket',
      category: "Men's Jackets",
      description: 'Military-inspired bomber jacket',
      images: [
        '/images/sample-products/p32-1.jpg',
        '/images/sample-products/p32-2.jpg',
      ],
      price: 165.00,
      brand: 'Alpha Industries',
      rating: 4.5,
      numReviews: 124,
      stock: 14,
      isFeatured: false,
      banner: null,
    },

    // Men's Sneakers
    {
      name: 'Nike Air Max 90',
      slug: 'nike-air-max-90',
      category: "Men's Sneakers",
      description: 'Iconic Air cushioning and timeless style',
      images: [
        '/images/sample-products/p33-1.jpg',
        '/images/sample-products/p33-2.jpg',
      ],
      price: 130.00,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 543,
      stock: 28,
      isFeatured: true,
      banner: 'banner-6.jpg',
    },
    {
      name: 'Adidas Ultraboost 22',
      slug: 'adidas-ultraboost-22',
      category: "Men's Sneakers",
      description: 'Energy-returning boost technology',
      images: [
        '/images/sample-products/p34-1.jpg',
        '/images/sample-products/p34-2.jpg',
      ],
      price: 190.00,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 412,
      stock: 23,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'New Balance 990v5',
      slug: 'new-balance-990v5',
      category: "Men's Sneakers",
      description: 'Made in USA with premium materials',
      images: [
        '/images/sample-products/p35-1.jpg',
        '/images/sample-products/p35-2.jpg',
      ],
      price: 185.00,
      brand: 'New Balance',
      rating: 4.9,
      numReviews: 289,
      stock: 19,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Converse Chuck Taylor All Star',
      slug: 'converse-chuck-taylor-all-star',
      category: "Men's Sneakers",
      description: 'Classic canvas sneaker since 1917',
      images: [
        '/images/sample-products/p36-1.jpg',
        '/images/sample-products/p36-2.jpg',
      ],
      price: 55.00,
      brand: 'Converse',
      rating: 4.6,
      numReviews: 1024,
      stock: 67,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Vans Old Skool',
      slug: 'vans-old-skool',
      category: "Men's Sneakers",
      description: 'Skate shoe icon with signature side stripe',
      images: [
        '/images/sample-products/p37-1.jpg',
        '/images/sample-products/p37-2.jpg',
      ],
      price: 65.00,
      brand: 'Vans',
      rating: 4.7,
      numReviews: 876,
      stock: 54,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Puma Suede Classic',
      slug: 'puma-suede-classic',
      category: "Men's Sneakers",
      description: 'Retro style with premium suede upper',
      images: [
        '/images/sample-products/p38-1.jpg',
        '/images/sample-products/p38-2.jpg',
      ],
      price: 70.00,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 234,
      stock: 31,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Reebok Classic Leather',
      slug: 'reebok-classic-leather',
      category: "Men's Sneakers",
      description: 'Minimalist design with soft garment leather',
      images: [
        '/images/sample-products/p39-1.jpg',
        '/images/sample-products/p39-2.jpg',
      ],
      price: 75.00,
      brand: 'Reebok',
      rating: 4.4,
      numReviews: 167,
      stock: 28,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Asics Gel-Lyte III',
      slug: 'asics-gel-lyte-iii',
      category: "Men's Sneakers",
      description: 'Japanese craftsmanship with split-tongue design',
      images: [
        '/images/sample-products/p40-1.jpg',
        '/images/sample-products/p40-2.jpg',
      ],
      price: 120.00,
      brand: 'Asics',
      rating: 4.6,
      numReviews: 145,
      stock: 17,
      isFeatured: false,
      banner: null,
    },

    // Men's T-Shirts
    {
      name: 'Hanes ComfortSoft Cotton Tee',
      slug: 'hanes-comfortsoft-cotton-tee',
      category: "Men's T-Shirts",
      description: 'Everyday essential in soft cotton',
      images: [
        '/images/sample-products/p41-1.jpg',
        '/images/sample-products/p41-2.jpg',
      ],
      price: 12.99,
      brand: 'Hanes',
      rating: 4.3,
      numReviews: 892,
      stock: 120,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Fruit of the Loom Crew Neck Tee 5-Pack',
      slug: 'fruit-of-the-loom-crew-neck-tee-5pack',
      category: "Men's T-Shirts",
      description: 'Value pack of comfortable basics',
      images: [
        '/images/sample-products/p42-1.jpg',
        '/images/sample-products/p42-2.jpg',
      ],
      price: 24.99,
      brand: 'Fruit of the Loom',
      rating: 4.2,
      numReviews: 654,
      stock: 85,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Gildan Ultra Cotton T-Shirt',
      slug: 'gildan-ultra-cotton-tshirt',
      category: "Men's T-Shirts",
      description: 'Heavy cotton tee for durability',
      images: [
        '/images/sample-products/p43-1.jpg',
        '/images/sample-products/p43-2.jpg',
      ],
      price: 9.99,
      brand: 'Gildan',
      rating: 4.1,
      numReviews: 1243,
      stock: 156,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Next Level Tri-Blend Crew Tee',
      slug: 'next-level-tri-blend-crew-tee',
      category: "Men's T-Shirts",
      description: 'Vintage feel with modern fit',
      images: [
        '/images/sample-products/p44-1.jpg',
        '/images/sample-products/p44-2.jpg',
      ],
      price: 18.99,
      brand: 'Next Level',
      rating: 4.7,
      numReviews: 412,
      stock: 73,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Bella + Canvas Unisex Jersey Tee',
      slug: 'bella-canvas-unisex-jersey-tee',
      category: "Men's T-Shirts",
      description: 'Retail fit with side seams',
      images: [
        '/images/sample-products/p45-1.jpg',
        '/images/sample-products/p45-2.jpg',
      ],
      price: 16.99,
      brand: 'Bella + Canvas',
      rating: 4.6,
      numReviews: 567,
      stock: 94,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'American Apparel Fine Jersey Tee',
      slug: 'american-apparel-fine-jersey-tee',
      category: "Men's T-Shirts",
      description: 'Slim fit made in USA',
      images: [
        '/images/sample-products/p46-1.jpg',
        '/images/sample-products/p46-2.jpg',
      ],
      price: 22.00,
      brand: 'American Apparel',
      rating: 4.5,
      numReviews: 298,
      stock: 47,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;